
services:
  db:
    image: mysql:latest
    container_name: dogWalker_mysql
    ports:
      - "3307:3306"
    networks:
      - dogWalker_mysql
  redis:
    image: redis:latest
    container_name: dogWalker_redis
    ports:
      - "6378:6379"
    networks:
      - dogWalker_mysql
networks:
  dogWalker_mysql:
    driver: bridge