
services:
  db:
    image: mysql:latest
    container_name: dogWalker_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "dogWalker"
      MYSQL_USER: "dogWalker"
      MYSQL_PASSWORD: "dogWalker"
      MYSQL_DATABASE: "dogWalker"
    networks:
      - dogWalker
  redis:
    image: redis:latest
    container_name: dogWalker_redis
    ports:
      - "6378:6379"
    networks:
      - dogWalker
networks:
  dogWalker:
    driver: bridge