
services:
  db:
    image: mysql:latest
    container_name: dogWalker_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "dogWalker"
      MYSQL_USER: "dogWalker"
      MYSQL_PASSWORD: "dogWalker"
      MYSQL_DATABASE: "dogWalker"
    networks:
      - dogWalker
  redis:
    image: redis:latest
    container_name: dogWalker_redis
    ports:
      - "6378:6379"
    networks:
      - dogWalker
  kafka:
    image: bitnami/kafka:latest
    container_name: dogWalker_kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dogWalker
networks:
  dogWalker:
    driver: bridge