
services:
  db:
    image: mysql:latest
    container_name: dogWalker_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "dogWalker"
      MYSQL_USER: "dogWalker"
      MYSQL_PASSWORD: "dogWalker"
      MYSQL_DATABASE: "dogWalker"
    networks:
      - dogWalker
  redis:
    image: redis:latest
    container_name: dogWalker_redis
    ports:
      - "6378:6379"
    networks:
      - dogWalker
  kafka:
    image: bitnami/kafka:latest
    container_name: dogWalker_kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dogWalker
networks:
  dogWalker:
    driver: bridge